### ISSUE TITLE
The updater needs git?

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/imagej-updater#84]
Hi all, hi @frauzufall 

I'm just updating a fresh Fiji on a fresh MacOS and it asks me to install git. Just wondering, is this intentional? If yes, Why? What is git doing in the background?

![DSC_1798](https://user-images.githubusercontent.com/12660498/70380241-34a03900-1938-11ea-9ecc-8d6f1120e18e.JPG)

Thanks!

Cheers,
Robert

**Comment by frauzufall** [comment]
What? Sorry, I have no idea where this comes from. The latest updater release is from September. We just tested a fresh Fiji and the updater on Gaby's Mac a few days ago and everything was fine. Sorry, might not be able to have a closer look before Monday.

**Comment by haesleinhuepf** [comment]
Could be an old issue... No hurry 😉

https://github.com/imagej/imagej-updater/blob/ab983dbd6c34dcf7ac2a4b85e857b0c0826db970/src/main/java/net/imagej/updater/Diff.java#L272

**Comment by imagejan** [comment]
I've seen this dialog only on macOS systems so far. The "updating" functionality of the updater is not affected when cancelling the dialog.

I'd suggest implementing a check for the presence of git and pass silently (or give a more informative message) when it's absent, instead of letting macOS handle it.

**Comment by ctrueden** [comment]
Bug fixed in imagej/imagej-ui-swing@cfaf9e3589d878084bee11dc6a777c0c3d9786d7.

I also uploaded a new imagej-ui-swing snapshot build to the update site. Please update your Fiji on an affected system and reopen this issue if the problem still persists.

P.S. While at it, I also added a system property `imagej.updater.git.command` which, when set, is used to call out to git, rather than using only `git` on the system path.

P.P.S. While at it, I also uploaded the newly released ImageJ 1.53q.
